# Generated by Django 3.1.2 on 2020-12-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='answer1',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='answer3',
        ),
    ]
